name: permission-whitelist-paper
version: '${project.version}'
main: org.smm.permissionwhitelistpaper.Main
api-version: '1.20'
authors:
  - SMMTeam
dependencies: 
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
permissions: 
  pwp.command.pwp:
    description: Permission to use /pwp command
    default: op